
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Muhammad Fakhruddin
 */
public class proton extends javax.swing.JFrame {

    /**
     * Creates new form proton
     */
    public proton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        resetBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTP = new javax.swing.JTextPane();
        sagaBtn = new javax.swing.JButton();
        personaBtn = new javax.swing.JButton();
        x50Btn = new javax.swing.JButton();
        x70Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROTON CARE");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel1.setText("SELECT YOUR CAR:");

        resetBtn.setText("RESET");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("EXIT");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(outputTP);

        sagaBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sagaBtn.setText("PROTON SAGA");
        sagaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sagaBtnActionPerformed(evt);
            }
        });

        personaBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        personaBtn.setText("PROTON PERSONA");
        personaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personaBtnActionPerformed(evt);
            }
        });

        x50Btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        x50Btn.setText("PROTON X50");
        x50Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x50BtnActionPerformed(evt);
            }
        });

        x70Btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        x70Btn.setText("PROTON X70");
        x70Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x70BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(93, 93, 93)
                            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(personaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addComponent(sagaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(93, 93, 93)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(x50Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(x70Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(sagaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(x50Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x70Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        outputTP.setText("");
        sagaBtn.setSelected(false);
        personaBtn.setSelected(false);
        x50Btn.setSelected(false);
        x70Btn.setSelected(false);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void personaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personaBtnActionPerformed
        outputTP.setText("Proton Persona"
			+"\nBasic Salary: RM 4,000"
			+ "\nMonthly installment: RM 599"
			+ "\nFeatures: 1.Shark Fin Antenna | 2.Rear Spoiler "
			+ "\nAccessories: 1.Sunshade | 2.Umbrella | 3.Air Freshener"
                        + "\nPrice OTR: 54,600");
    }//GEN-LAST:event_personaBtnActionPerformed

    private void sagaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sagaBtnActionPerformed
      
            outputTP.setText( "Proton Saga"
				+"\nBasic Salary: RM 2,500"
				+ "\nMonthly installment: RM 440"
				+ "\nFeatures: 1.Duluxe Seat Fabrics | 2.ABS, EBD and BA | 3.Trunk Room Lamp"
				+ "\nAccessories: 1.Sunshade | 2.Umbrella | 3.Air Freshener"
                                + "\nPrice OTR: 39,800");
				
    }//GEN-LAST:event_sagaBtnActionPerformed

    private void x50BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x50BtnActionPerformed
        outputTP.setText("Proton X50"
			+"\nBasic Salary: RM 4,700"
			+ "\nMonthly installment: RM 1,169"
			+ "\nFeatures: 1.7-speed Dual Clutch Transmission, 2.360 Camera and Parking Sensors | 3.17' Alloy Wheels"
			+ "\nAccessories: 1.Sunshade | 2.Umbrella | 3.Air Freshener"
                        + "\nPrice OTR: 103,100");
    }//GEN-LAST:event_x50BtnActionPerformed

    private void x70BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x70BtnActionPerformed
        outputTP.setText("Proton X70"
			+"\nBasic Salary: RM 5,500"
			+ "\nMonthly installment: RM 1,219"
			+ "\nFeatures: 1.Halogen Headlamps, 2.Panoramis Sunroof | 3.17' Alloy Wheels"
			+ "\nAccessories: 1.Sunshade | 2.Umbrella | 3.Air Freshener"
                        + "\nPrice OTR: 122,800");
    }//GEN-LAST:event_x70BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane outputTP;
    private javax.swing.JButton personaBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton sagaBtn;
    private javax.swing.JButton x50Btn;
    private javax.swing.JButton x70Btn;
    // End of variables declaration//GEN-END:variables
}
